### **Transaction Additional : -**

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [4]:
import dask.dataframe as dd
df_batch1 = dd.read_parquet("transactions_additional/batch-1/*.parquet")
df_batch2 = dd.read_parquet("transactions_additional/batch-2/*.parquet")
df_batch3 = dd.read_parquet("transactions_additional/batch-3/*.parquet")
df_batch4 = dd.read_parquet("transactions_additional/batch-4/*.parquet")

In [24]:
import dask.dataframe as dd
df_batch5 = dd.read_parquet("transactions/batch-1/*.parquet")
df_batch6 = dd.read_parquet("transactions/batch-2/*.parquet")
df_batch7 = dd.read_parquet("transactions/batch-3/*.parquet")
df_batch8 = dd.read_parquet("transactions/batch-4/*.parquet")

In [5]:
df_batch1.head()

,transaction_id,mnemonic_code,latitude,longitude,ip_address,balance_after_transaction,part_transaction_type,atm_deposit_channel_code,transaction_sub_type
0,TXN_0000000000,END,NaN,NaN,122.175.102.100,53657.59,CI,<NA>,normal
1,TXN_0000000001,UPD,15.786843,78.077894,103.92.190.204,53479.10,CI,<NA>,normal
2,TXN_0000000002,CCL,NaN,NaN,<NA>,52479.10,CI,<NA>,normal
3,TXN_0000000003,UPC,15.781886,78.053709,122.124.163.67,59479.10,CI,<NA>,normal
4,TXN_0000000004,FTD,NaN,NaN,103.241.164.38,64179.10,CI,<NA>,normal

In [6]:
df_batch2.head()

,transaction_id,mnemonic_code,latitude,longitude,ip_address,balance_after_transaction,part_transaction_type,atm_deposit_channel_code,transaction_sub_type
0,TXN_0129898887,CHQ,NaN,NaN,<NA>,-6539390.52,CI,<NA>,normal
1,TXN_0129898888,MCR,NaN,NaN,<NA>,-6539290.52,CI,<NA>,normal
2,TXN_0129898889,UPC,NaN,NaN,<NA>,-6687290.52,CI,<NA>,normal
3,TXN_0129898890,END,NaN,NaN,<NA>,-6684524.33,CI,<NA>,normal
4,TXN_0129898891,END,30.362281,78.051806,<NA>,-6684347.01,CI,<NA>,normal

In [7]:
df_batch3.head()

,transaction_id,mnemonic_code,latitude,longitude,ip_address,balance_after_transaction,part_transaction_type,atm_deposit_channel_code,transaction_sub_type
0,TXN_0256314037,UPD,NaN,NaN,<NA>,404235.51,CI,<NA>,normal
1,TXN_0256314038,UPC,NaN,NaN,106.166.225.83,404085.32,CI,<NA>,normal
2,TXN_0256314039,UPD,NaN,NaN,106.254.54.154,405085.32,CI,<NA>,normal
3,TXN_0256314040,UPC,NaN,NaN,<NA>,416085.32,CI,<NA>,normal
4,TXN_0256314041,UPD,24.565365,73.715468,<NA>,503585.32,CI,<NA>,normal

In [27]:
df_batch1.head()

,transaction_id,mnemonic_code,latitude,longitude,ip_address,balance_after_transaction,part_transaction_type,atm_deposit_channel_code,transaction_sub_type
0,TXN_0000000000,END,NaN,NaN,122.175.102.100,53657.59,CI,<NA>,normal
1,TXN_0000000001,UPD,15.786843,78.077894,103.92.190.204,53479.10,CI,<NA>,normal
2,TXN_0000000002,CCL,NaN,NaN,<NA>,52479.10,CI,<NA>,normal
3,TXN_0000000003,UPC,15.781886,78.053709,122.124.163.67,59479.10,CI,<NA>,normal
4,TXN_0000000004,FTD,NaN,NaN,103.241.164.38,64179.10,CI,<NA>,normal

In [29]:
df_batch5.head()

,transaction_id,account_id,transaction_timestamp,mcc_code,channel,amount,txn_type,counterparty_id
0,TXN_0001000000,ACCT_000494,2023-05-22T22:47:35,9384,UPD,299.55,C,CP_090625
1,TXN_0001000001,ACCT_000494,2023-05-22T22:53:31,2943,MAC,11191.27,D,CP_070045
2,TXN_0001000002,ACCT_000494,2023-05-23T01:40:04,5651,UPC,159.42,D,CP_029345
3,TXN_0001000003,ACCT_000494,2023-05-23T05:48:59,6101,UPD,23700.00,D,CP_038556
4,TXN_0001000004,ACCT_000494,2023-05-23T10:33:24,5651,UPD,2000.00,D,CP_000291

In [10]:
print(df_batch1.isnull().sum().compute())
print("================================================================")
print(df_batch2.isnull().sum().compute())
print("================================================================")
print(df_batch3.isnull().sum().compute())
print("================================================================")
print(df_batch4.isnull().sum().compute())

transaction_id                       0
mnemonic_code                        0
latitude                      88098798
longitude                     88098798
ip_address                    84937458
balance_after_transaction            0
part_transaction_type                0
atm_deposit_channel_code     129545038
transaction_sub_type                 0
dtype: int64
================================================================
transaction_id                       0
mnemonic_code                        0
latitude                      81965959
longitude                     81965959
ip_address                    82659699
balance_after_transaction            0
part_transaction_type                0
atm_deposit_channel_code     126070378
transaction_sub_type                 0
dtype: int64
================================================================
transaction_id                       0
mnemonic_code                        0
latitude                      84251907
longitude                     84251907
ip_address                    84259373
balance_after_transaction            0
part_transaction_type                0
atm_deposit_channel_code     128525897
transaction_sub_type                 0
dtype: int64
================================================================
transaction_id                      0
mnemonic_code                       0
latitude                      8046824
longitude                     8046824
ip_address                    8455963
balance_after_transaction           0
part_transaction_type               0
atm_deposit_channel_code     12652221
transaction_sub_type            38121
dtype: int64

In [30]:
print(df_batch5.isnull().sum().compute())
print("================================================================")
print(df_batch6.isnull().sum().compute())
print("================================================================")
print(df_batch7.isnull().sum().compute())
print("================================================================")
print(df_batch8.isnull().sum().compute())

transaction_id           0
account_id               0
transaction_timestamp    0
mcc_code                 0
channel                  0
amount                   0
txn_type                 0
counterparty_id          0
dtype: int64
================================================================
transaction_id           0
account_id               0
transaction_timestamp    0
mcc_code                 0
channel                  0
amount                   0
txn_type                 0
counterparty_id          0
dtype: int64
================================================================
transaction_id           0
account_id               0
transaction_timestamp    0
mcc_code                 0
channel                  0
amount                   0
txn_type                 0
counterparty_id          0
dtype: int64
================================================================
transaction_id           0
account_id               0
transaction_timestamp    0
mcc_code                 0
channel                  0
amount                   0
txn_type                 0
counterparty_id          0
dtype: int64

In [ ]:
df_batch1.isnull().sum().compute()

In [8]:
df_batch1.shape[0].compute()

129898887

In [21]:
print(f"batch1 : {df_batch1.shape[0].compute()} x {df_batch1.shape[1]}")
print(f"batch2 : {df_batch2.shape[0].compute()} x {df_batch2.shape[1]}")
print(f"batch3 : {df_batch3.shape[0].compute()} x {df_batch3.shape[1]}")
print(f"batch4 : {df_batch4.shape[0].compute()} x {df_batch4.shape[1]}")

batch1 : 129898887 x 9
batch2 : 126415150 x 9
batch3 : 128875774 x 9
batch4 : 12685512 x 9

In [31]:
print(f"batch5 : {df_batch5.shape[0].compute()} x {df_batch5.shape[1]}")
print(f"batch6 : {df_batch6.shape[0].compute()} x {df_batch6.shape[1]}")
print(f"batch7 : {df_batch7.shape[0].compute()} x {df_batch7.shape[1]}")
print(f"batch8 : {df_batch8.shape[0].compute()} x {df_batch8.shape[1]}")

batch5 : 99686033 x 8
batch6 : 100407662 x 8
batch7 : 100460390 x 8
batch8 : 96321238 x 8