In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [33]:
import pandas as pd
df = pd.read_csv("outputs\suspicious_windows.csv")
print(df.shape)
df.head()

(64062, 7)

,account_id,is_mule,suspicious_start,suspicious_end,suspicious_months,peak_zscore,confidence
0,ACCT_001376,1,2025-06-01 02:35:54,2025-06-28 14:05:00,1,20.0,medium
1,ACCT_004141,1,2020-10-25 21:46:42,2025-06-28 12:00:00,27,20.0,high
2,ACCT_009729,1,2025-06-01 00:08:27,2025-06-29 12:41:35,1,20.0,medium
3,ACCT_011082,1,2025-06-01 00:12:50,2025-06-29 14:36:46,1,20.0,medium
4,ACCT_012425,1,2025-06-03 19:33:00,2025-06-30 00:00:00,1,20.0,medium

In [34]:
df_new = df.drop(columns=["suspicious_months","peak_zscore","confidence"])

In [35]:
df_new.head()

    account_id  is_mule     suspicious_start       suspicious_end
0  ACCT_001376        1  2025-06-01 02:35:54  2025-06-28 14:05:00
1  ACCT_004141        1  2020-10-25 21:46:42  2025-06-28 12:00:00
2  ACCT_009729        1  2025-06-01 00:08:27  2025-06-29 12:41:35
3  ACCT_011082        1  2025-06-01 00:12:50  2025-06-29 14:36:46
4  ACCT_012425        1  2025-06-03 19:33:00  2025-06-30 00:00:00

In [36]:
df_new.isnull().sum()

account_id              0
is_mule                 0
suspicious_start    63362
suspicious_end      63362
dtype: int64

In [37]:
df_new.is_mule.value_counts()

is_mule
0    62807
1     1255
Name: count, dtype: int64

In [38]:
df_new.shape

(64062, 4)

In [39]:
df_test  = pd.read_parquet("test_accounts.parquet")
print(df_test.shape)
df_test.head()

(64062, 1)

    account_id
0  ACCT_000005
1  ACCT_000007
2  ACCT_000009
3  ACCT_000015
4  ACCT_000016

In [41]:
df_test  = pd.read_csv("s2.csv")
print(df_test.shape)
df_test.head()

(64062, 2)

    account_id  is_mule
0  ACCT_000005        0
1  ACCT_000007        0
2  ACCT_000009        0
3  ACCT_000015        0
4  ACCT_000016        0

In [42]:
df_merged = pd.merge(
    df_test,
    df[["account_id","suspicious_start", "suspicious_end"]],  # select only important columns
    on="account_id",
    how="left"
)
df_merged.shape

(64062, 4)

In [43]:
df_merged.head()

    account_id  is_mule suspicious_start suspicious_end
0  ACCT_000005        0              NaN            NaN
1  ACCT_000007        0              NaN            NaN
2  ACCT_000009        0              NaN            NaN
3  ACCT_000015        0              NaN            NaN
4  ACCT_000016        0              NaN            NaN

In [44]:
df_merged.to_csv("w2.csv",index=False)