In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)

In [2]:
df = pd.read_parquet("df_final2.parquet")
print(df.shape)
df.head()

(160153, 131)

,account_id,account_status,avg_balance_x,product_family,nomination_flag,cheque_allowed,cheque_availed,num_chequebooks,kyc_compliant,rural_branch,monthly_avg_balance,quarterly_avg_balance,daily_avg_balance,branch_employee_count,branch_turnover,branch_asset_size,branch_type,scheme_code,pan_available,passport_available,mobile_banking_flag,internet_banking_flag,atm_card_flag,demat_flag,credit_card_flag,fastag_flag,joint_account_flag,nri_flag,loan_sum,loan_count,cc_sum,cc_count,od_sum,od_count,ka_sum,ka_count,sa_sum,sa_count,total_transactions,unique_mcc_count,most_common_mcc,max_mcc_frequency,mcc_max_amount,mcc_min_amount,unique_channel_count,max_channel_frequency,avg_unique_mcc_per_hour,avg_unique_mcc_per_day,avg_unique_channel_per_hour,avg_unique_channel_per_day,least_common_mcc_code,total_transaction_amount,avg_transaction_amount,max_transaction_amount,min_transaction_amount,std_transaction_amount,median_transaction_amount,total_credit_amount,total_debit_amount,max_credit_amount,max_debit_amount,credit_debit_ratio,credit_ratio,debit_ratio,avg_time_between_txn_sec,median_time_between_txn_sec,max_txn_1hr,max_txn_10min,max_txn_1day,max_txn_1week,avg_txn_per_day,avg_txn_per_hr,avg_txn_per_week,avg_txn_per_month,night_txn_rate,day_txn_rate,rapid_passthrough_count,unique_counterparty_count,repeated_counterparty_frequency,unique_credit_counterparty_count,unique_debit_counterparty_count,avg_unique_counterparty_1hr,max_unique_counterparty_1hr,avg_repeated_counterparty_freq_1hr,avg_unique_counterparty_1day,max_unique_counterparty_1day,avg_repeated_counterparty_freq_1day,geo_txn_count,geo_frac,unique_geo_count,geo_bbox_km,has_geo_flag,ip_txn_count,ip_frac,unique_ip_count,top_ip_count,top_ip_share,atm_deposit_count,atm_deposit_frac,avg_balance_y,min_balance,avg_balance_credit,avg_balance_debit,max_balance,clt_cash_ratio,loan_ratio,normal_ratio,ci_ratio,bi_ratio,ip_ratio,ic_ratio,avg_unique_ip_hour,max_unique_ip_hour,avg_unique_ip_day,max_unique_ip_day,is_mule,days_since_account_open,account_open_issue_flag,avg_balance_missing,active_tenure_days,monthly_avg_balance_missing,account_frozen_flag,zero_transaction_flag,least_common_channel_group,most_common_channel_group,uses_cdm,uses_crm,uses_both_atm,no_atm_deposit,duplicate_customer_flag,aadhaar_available
0,ACCT_000000,0,53720.31,1,1,1,1,0,1,1,50111.60,55554.79,66771.57,41,13.14,227.69,0,1,1,0,1,1,1,0,1,0,0,0,0.00,0,117176.98,1,0.00,0,53720.31,1,0.0,0,0.0,0.0,-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45425573.0,45900340.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,792.0,1,0,1427,0,0,1,5,5,0,0,0,1,0,1.0
1,ACCT_000002,0,9492.82,2,0,0,0,0,1,0,9169.02,6925.45,8737.84,3,12.47,489.68,1,0,0,0,1,0,1,0,0,0,0,0,0.00,0,0.00,0,-25821.38,1,0.00,0,0.0,0,0.0,0.0,-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45425573.0,45900340.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,792.0,1,0,7291,0,0,1,5,5,0,0,0,1,0,0.0
2,ACCT_000003,0,93286.70,0,0,1,1,3,1,0,86326.00,100171.75,78181.17,31,12.24,343.44,1,0,0,0,0,0,1,0,0,0,0,0,-158176.92,2,0.00,0,0.00,0,0.00,0,93286.7,1,0.0,0.0,-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45425573.0,45900340.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,792.0,1,0,2012,0,0,1,5,5,0,0,0,1,0,1.0
3,ACCT_000004,0,555715.54,1,1,1,0,0,1,0,647193.23,509836.62,699191.21,21,5.64,478.34,0,1,0,1,0,0,0,0,1,0,0,0,0.00,0,-125254.73,1,0.00,0,555715.54,1,0.0,0,0.0,0.0,-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45425573.0,45900340.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,792.0,1,0,4252,0,0,1,5,5,0,0,0,1,0,-1.0
4,ACCT_000005,0,16380.55,1,0,1,0,0,1,0,15878.60,13651.60,21249.07,37,21.98,372.88,0,0,1,0,1,1,0,0,1,0,0,0,0.00,0,-15874.35,2,0.00,0,16380.55,1,0.0,0,0.0,0.0,-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45425573.0,45900340.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1,792.0,1,0,5807,0,0,1,5,5,0,0,0,1,0,1.0

In [3]:
df.isnull().sum()

account_id                             0
account_status                         0
avg_balance_x                          0
product_family                         0
nomination_flag                        0
cheque_allowed                         0
cheque_availed                         0
num_chequebooks                        0
kyc_compliant                          0
rural_branch                           0
monthly_avg_balance                    0
quarterly_avg_balance                  0
daily_avg_balance                      0
branch_employee_count                  0
branch_turnover                        0
branch_asset_size                      0
branch_type                            0
scheme_code                            0
pan_available                          0
passport_available                     0
mobile_banking_flag                    0
internet_banking_flag                  0
atm_card_flag                          0
demat_flag                             0
credit_card_flag                       0
fastag_flag                            0
joint_account_flag                     0
nri_flag                               0
loan_sum                               0
loan_count                             0
cc_sum                                 0
cc_count                               0
od_sum                                 0
od_count                               0
ka_sum                                 0
ka_count                               0
sa_sum                                 0
sa_count                               0
total_transactions                     0
unique_mcc_count                       0
most_common_mcc                        0
max_mcc_frequency                      0
mcc_max_amount                         0
mcc_min_amount                         0
unique_channel_count                   0
max_channel_frequency                  0
avg_unique_mcc_per_hour                0
avg_unique_mcc_per_day                 0
avg_unique_channel_per_hour            0
avg_unique_channel_per_day             0
least_common_mcc_code                  0
total_transaction_amount               0
avg_transaction_amount                 0
max_transaction_amount                 0
min_transaction_amount                 0
std_transaction_amount                 0
median_transaction_amount              0
total_credit_amount                    0
total_debit_amount                     0
max_credit_amount                      0
max_debit_amount                       0
credit_debit_ratio                     0
credit_ratio                           0
debit_ratio                            0
avg_time_between_txn_sec               0
median_time_between_txn_sec            0
max_txn_1hr                            0
max_txn_10min                          0
max_txn_1day                           0
max_txn_1week                          0
avg_txn_per_day                        0
avg_txn_per_hr                         0
avg_txn_per_week                       0
avg_txn_per_month                      0
night_txn_rate                         0
day_txn_rate                           0
rapid_passthrough_count                0
unique_counterparty_count              0
repeated_counterparty_frequency        0
unique_credit_counterparty_count       0
unique_debit_counterparty_count        0
avg_unique_counterparty_1hr            0
max_unique_counterparty_1hr            0
avg_repeated_counterparty_freq_1hr     0
avg_unique_counterparty_1day           0
max_unique_counterparty_1day           0
avg_repeated_counterparty_freq_1day    0
geo_txn_count                          0
geo_frac                               0
unique_geo_count                       0
geo_bbox_km                            0
has_geo_flag                           0
ip_txn_count                           0
ip_frac                                0
unique_ip_count                        0
top_ip_count                           0
top_ip_share                           0
atm_deposit_count                      0
atm_deposit_frac                       0
avg_balance_y                          0
min_balance                            0
avg_balance_credit                     0
avg_balance_debit                      0
max_balance                            0
clt_cash_ratio                         0
loan_ratio                             0
normal_ratio                           0
ci_ratio                               0
bi_ratio                               0
ip_ratio                               0
ic_ratio                               0
avg_unique_ip_hour                     0
max_unique_ip_hour                     0
avg_unique_ip_day                      0
max_unique_ip_day                      0
is_mule                                0
days_since_account_open                0
account_open_issue_flag                0
avg_balance_missing                    0
active_tenure_days                     0
monthly_avg_balance_missing            0
account_frozen_flag                    0
zero_transaction_flag                  0
least_common_channel_group             0
most_common_channel_group              0
uses_cdm                               0
uses_crm                               0
uses_both_atm                          0
no_atm_deposit                         0
duplicate_customer_flag                0
aadhaar_available                      0
dtype: int64

### **Drop sum more column :-**

In [4]:
FINAL_DROP = [

    
    # Duplicates — perfectly correlated with columns you already have
    "avg_balance_y",          # duplicate of avg_balance_x
    "quarterly_avg_balance",  # correlated with monthly_avg_balance
    "daily_avg_balance",      # correlated with avg_balance_x
    "credit_ratio",           # = 1 - debit_ratio
    "debit_ratio",            # keep credit_debit_ratio instead
    "day_txn_rate",           # = 1 - night_txn_rate
    "avg_txn_per_week",       # correlated with avg_txn_per_day
    "avg_txn_per_month",      # correlated with avg_txn_per_day
    "max_txn_1week",          # correlated with max_txn_1day
    
    # Admin — branch operational metrics, not account behaviour
    "branch_employee_count",
    "branch_turnover",
    "branch_asset_size",
    "branch_type",
    "scheme_code",
    "currency_code",          # near zero variance — almost all INR
    "num_chequebooks",        # cheque_availed already captures this
    
    # High cardinality strings still remaining
    "most_common_mcc",        # needs frequency encoding or drop
    "least_common_mcc_code",  # needs frequency encoding or drop
]

df = df.drop(columns=[c for c in FINAL_DROP if c in df.columns])
print(f"Dropped : {len([c for c in FINAL_DROP if c in df.columns])} columns")
print(f"Remaining : {df.shape[1]} columns")

Dropped : 0 columns
Remaining : 114 columns

In [5]:
df_train = pd.read_parquet("train_labels.parquet")
print(df_train.shape)
df_train.is_mule.value_counts()

(96091, 5)

is_mule
0    93408
1     2683
Name: count, dtype: int64

In [6]:
df.shape

(160153, 114)

In [7]:
df_train = df[df["is_mule"] != -1]
print(df_train.shape)
# df_train.value_counts()

(96091, 114)

In [8]:
# df_train.to_parquet("df_final3.parqet",index = False)

In [9]:
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (classification_report, roc_auc_score,
                             average_precision_score, confusion_matrix,
                             f1_score, precision_recall_curve)
import lightgbm as lgb
import xgboost as xgb
from imblearn.combine import SMOTETomek
import warnings
warnings.filterwarnings("ignore")

In [10]:
X = df_train.drop(columns=["is_mule","account_id"],axis = 1)
y = df_train["is_mule"]

print(f"Features : {X.shape[1]}")
print(f"Mule rate: {y.mean():.4f}")

Features : 112
Mule rate: 0.0279

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)
print(f"\nTrain shape : {X_train.shape}")
print(f"Test shape  : {X_test.shape}")
print(f"Train mules : {y_train.sum()} ({y_train.mean():.4f})")
print(f"Test mules  : {y_test.sum()} ({y_test.mean():.4f})")

Train shape : (76872, 112)
Test shape  : (19219, 112)
Train mules : 2146 (0.0279)
Test mules  : 537 (0.0279)

Applt smoth and tomek: -

In [ ]:
# # SMOTE creates synthetic mule samples
# # Tomek links removes borderline majority samples
# # Together they give the cleanest decision boundary
# from imblearn.combine import SMOTETomek
# smt = SMOTETomek(random_state=42)
# X_train_res, y_train_res = smt.fit_resample(X_train, y_train)
# print(f"\nAfter SMOTETomek:")
# print(f"Train shape : {X_train_res.shape}")
# print(pd.Series(y_train_res).value_counts())

After SMOTETomek:
Train shape : (149146, 112)
is_mule
0    74573
1    74573
Name: count, dtype: int64

In [13]:
# ── LightGBM — best model for this type of data ─────────────
# scale_pos_weight not needed after SMOTETomek
# but class_weight='balanced' adds extra safety
lgbm = lgb.LGBMClassifier(
    n_estimators      = 1000,
    learning_rate     = 0.05,
    num_leaves        = 63,
    max_depth         = -1,
    min_child_samples = 20,
    subsample         = 0.8,
    colsample_bytree  = 0.8,
    reg_alpha         = 0.1,
    reg_lambda        = 0.1,
    class_weight      = "balanced",
    random_state      = 42,
    n_jobs            = -1,
    verbose           = -1
)

lgbm.fit(
    X_train, y_train,
    eval_set=[(X_test, y_test)],
    callbacks=[lgb.early_stopping(50, verbose=False),
               lgb.log_evaluation(100)]
)

# ── Evaluate ─────────────────────────────────────────────────
y_pred  = lgbm.predict(X_test)
y_proba = lgbm.predict_proba(X_test)[:, 1]

print("\n" + "="*50)
print("LIGHTGBM RESULTS")
print("="*50)
print(f"ROC-AUC  : {roc_auc_score(y_test, y_proba):.4f}")
print(f"PR-AUC   : {average_precision_score(y_test, y_proba):.4f}")
print(f"F1-Mule  : {f1_score(y_test, y_pred):.4f}")
print(f"F1-Macro : {f1_score(y_test, y_pred, average='macro'):.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred,
      target_names=["legit", "mule"]))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

[100]	valid_0's binary_logloss: 0.126622
[200]	valid_0's binary_logloss: 0.0841215
[300]	valid_0's binary_logloss: 0.0694464
[400]	valid_0's binary_logloss: 0.0629032
[500]	valid_0's binary_logloss: 0.0615037

==================================================
LIGHTGBM RESULTS
==================================================
ROC-AUC  : 0.9339
PR-AUC   : 0.6823
F1-Mule  : 0.7276
F1-Macro : 0.8596

Classification Report:
              precision    recall  f1-score   support

       legit       0.99      0.99      0.99     18682
        mule       0.69      0.77      0.73       537

    accuracy                           0.98     19219
   macro avg       0.84      0.88      0.86     19219
weighted avg       0.98      0.98      0.98     19219

Confusion Matrix:
[[18495   187]
 [  123   414]]

In [14]:
# # ── LightGBM — best model for this type of data ─────────────
# # scale_pos_weight not needed after SMOTETomek
# # but class_weight='balanced' adds extra safety
# lgbm = lgb.LGBMClassifier(
#     n_estimators      = 1000,
#     learning_rate     = 0.05,
#     num_leaves        = 63,
#     max_depth         = -1,
#     min_child_samples = 20,
#     subsample         = 0.8,
#     colsample_bytree  = 0.8,
#     reg_alpha         = 0.1,
#     reg_lambda        = 0.1,
#     class_weight      = "balanced",
#     random_state      = 42,
#     n_jobs            = -1,
#     verbose           = -1
# )

# lgbm.fit(
#     X_train_res, y_train_res,
#     eval_set=[(X_test, y_test)],
#     callbacks=[lgb.early_stopping(50, verbose=False),
#                lgb.log_evaluation(100)]
# )

# # ── Evaluate ─────────────────────────────────────────────────
# y_pred  = lgbm.predict(X_test)
# y_proba = lgbm.predict_proba(X_test)[:, 1]

# print("\n" + "="*50)
# print("LIGHTGBM RESULTS")
# print("="*50)
# print(f"ROC-AUC  : {roc_auc_score(y_test, y_proba):.4f}")
# print(f"PR-AUC   : {average_precision_score(y_test, y_proba):.4f}")
# print(f"F1-Mule  : {f1_score(y_test, y_pred):.4f}")
# print(f"F1-Macro : {f1_score(y_test, y_pred, average='macro'):.4f}")
# print("\nClassification Report:")
# print(classification_report(y_test, y_pred,
#       target_names=["legit", "mule"]))
# print("Confusion Matrix:")
# print(confusion_matrix(y_test, y_pred))

In [15]:
# precisions, recalls, thresholds = precision_recall_curve(y_test, y_proba)
# target_recall = 0.85
# idx = np.argmax(recalls >= target_recall)
# best_threshold = thresholds[max(idx - 1, 0)]

# y_pred_tuned = (y_proba >= best_threshold).astype(int)
# print(f"\nTuned threshold : {best_threshold:.4f}")
# print(f"After tuning:")
# print(classification_report(y_pred_tuned, y_test,
#       target_names=["legit", "mule"]))

### **Apply random forest : -**

In [16]:
# from sklearn.ensemble import RandomForestClassifier
# rf_model = RandomForestClassifier(
#     n_estimators=300,
#     max_depth=15,
#     min_samples_split=5,
#     min_samples_leaf=2,
#     n_jobs=-1,
#     random_state=42,
#     class_weight="balanced"
# )

# rf_model.fit(X_train, y_train)
# y_pred  = rf_model.predict(X_test)
# y_proba = rf_model.predict_proba(X_test)[:, 1]

# print("\n" + "="*50)
# print("LIGHTGBM RESULTS")
# print("="*50)
# print(f"ROC-AUC  : {roc_auc_score(y_test, y_proba):.4f}")
# print(f"PR-AUC   : {average_precision_score(y_test, y_proba):.4f}")
# print(f"F1-Mule  : {f1_score(y_test, y_pred):.4f}")
# print(f"F1-Macro : {f1_score(y_test, y_pred, average='macro'):.4f}")
# print("\nClassification Report:")
# print(classification_report(y_test, y_pred,
#       target_names=["legit", "mule"]))
# print("Confusion Matrix:")
# print(confusion_matrix(y_test, y_pred))

In [17]:
# y_pred  = rf_model.predict(X_test)
# y_proba = rf_model.predict_proba(X_test)[:, 1]

# print("\n" + "="*50)
# print("LIGHTGBM RESULTS")
# print("="*50)
# print(f"ROC-AUC  : {roc_auc_score(y_test, y_proba):.4f}")
# print(f"PR-AUC   : {average_precision_score(y_test, y_proba):.4f}")
# print(f"F1-Mule  : {f1_score(y_test, y_pred):.4f}")
# print(f"F1-Macro : {f1_score(y_test, y_pred, average='macro'):.4f}")
# print("\nClassification Report:")
# print(classification_report(y_test, y_pred,
#       target_names=["legit", "mule"]))
# print("Confusion Matrix:")
# print(confusion_matrix(y_test, y_pred))

In [18]:
# from sklearn.ensemble import RandomForestClassifier
# rf_model = RandomForestClassifier(
#     n_estimators=300,
#     max_depth=15,
#     min_samples_split=5,
#     min_samples_leaf=2,
#     n_jobs=-1,
#     random_state=42,
#     class_weight="balanced"
# )

# rf_model.fit(X_train_res, y_train_res)
# y_pred  = rf_model.predict(X_test)
# y_proba = rf_model.predict_proba(X_test)[:, 1]

# print("\n" + "="*50)
# print("LIGHTGBM RESULTS")
# print("="*50)
# print(f"ROC-AUC  : {roc_auc_score(y_test, y_proba):.4f}")
# print(f"PR-AUC   : {average_precision_score(y_test, y_proba):.4f}")
# print(f"F1-Mule  : {f1_score(y_test, y_pred):.4f}")
# print(f"F1-Macro : {f1_score(y_test, y_pred, average='macro'):.4f}")
# print("\nClassification Report:")
# print(classification_report(y_test, y_pred,
#       target_names=["legit", "mule"]))
# print("Confusion Matrix:")
# print(confusion_matrix(y_test, y_pred))

In [19]:
# from catboost import CatBoostClassifier
# cat_model = CatBoostClassifier(
#     iterations=1000,
#     depth=8,
#     learning_rate=0.05,
#     loss_function='Logloss',
#     eval_metric='AUC',
#     random_seed=42,
#     verbose=100
# )

# cat_model.fit(X_train, y_train)
# y_pred = cat_model.predict(X_test)
# y_prob = cat_model.predict_proba(X_test)[:,1]
# print("Confusion Matrix")
# print(confusion_matrix(y_test, y_pred))

# print("\nClassification Report")
# print(classification_report(y_test, y_pred))

# print("\nROC AUC Score")
# print(roc_auc_score(y_test, y_prob))
# print(f"ROC-AUC  : {roc_auc_score(y_test, y_proba):.4f}")
# print(f"PR-AUC   : {average_precision_score(y_test, y_proba):.4f}")
# print(f"F1-Mule  : {f1_score(y_test, y_pred):.4f}")
# print(f"F1-Macro : {f1_score(y_test, y_pred, average='macro'):.4f}")
# print("\nClassification Report:")
# print(classification_report(y_test, y_pred,
#       target_names=["legit", "mule"]))
# print("Confusion Matrix:")
# print(confusion_matrix(y_test, y_pred))

In [20]:
# import xgboost as xgb
# xgb_model = xgb.XGBClassifier(
#     n_estimators=500,
#     max_depth=8,
#     learning_rate=0.05,
#     subsample=0.8,
#     colsample_bytree=0.8,
#     random_state=42,
#     n_jobs=-1,
#     eval_metric="logloss"
# )

# xgb_model.fit(X_train_res, y_train_res)
# print("Confusion Matrix")
# print(confusion_matrix(y_test, y_pred))

# print("\nClassification Report")
# print(classification_report(y_test, y_pred))

# print("\nROC AUC Score")
# print(roc_auc_score(y_test, y_prob))

make csv

In [21]:
df_test = pd.read_parquet("test_accounts.parquet")
print(df_test.shape)
df_test.head()

(64062, 1)

    account_id
0  ACCT_000005
1  ACCT_000007
2  ACCT_000009
3  ACCT_000015
4  ACCT_000016

In [22]:
df.shape

(160153, 114)

In [23]:
df_merged = pd.merge(df_test, df, on="account_id", how="left")
print(df_merged.shape)
df_merged.head(5)

(64062, 114)

,account_id,account_status,avg_balance_x,product_family,nomination_flag,cheque_allowed,cheque_availed,kyc_compliant,rural_branch,monthly_avg_balance,pan_available,passport_available,mobile_banking_flag,internet_banking_flag,atm_card_flag,demat_flag,credit_card_flag,fastag_flag,joint_account_flag,nri_flag,loan_sum,loan_count,cc_sum,cc_count,od_sum,od_count,ka_sum,ka_count,sa_sum,sa_count,total_transactions,unique_mcc_count,max_mcc_frequency,mcc_max_amount,mcc_min_amount,unique_channel_count,max_channel_frequency,avg_unique_mcc_per_hour,avg_unique_mcc_per_day,avg_unique_channel_per_hour,avg_unique_channel_per_day,total_transaction_amount,avg_transaction_amount,max_transaction_amount,min_transaction_amount,std_transaction_amount,median_transaction_amount,total_credit_amount,total_debit_amount,max_credit_amount,max_debit_amount,credit_debit_ratio,avg_time_between_txn_sec,median_time_between_txn_sec,max_txn_1hr,max_txn_10min,max_txn_1day,avg_txn_per_day,avg_txn_per_hr,night_txn_rate,rapid_passthrough_count,unique_counterparty_count,repeated_counterparty_frequency,unique_credit_counterparty_count,unique_debit_counterparty_count,avg_unique_counterparty_1hr,max_unique_counterparty_1hr,avg_repeated_counterparty_freq_1hr,avg_unique_counterparty_1day,max_unique_counterparty_1day,avg_repeated_counterparty_freq_1day,geo_txn_count,geo_frac,unique_geo_count,geo_bbox_km,has_geo_flag,ip_txn_count,ip_frac,unique_ip_count,top_ip_count,top_ip_share,atm_deposit_count,atm_deposit_frac,min_balance,avg_balance_credit,avg_balance_debit,max_balance,clt_cash_ratio,loan_ratio,normal_ratio,ci_ratio,bi_ratio,ip_ratio,ic_ratio,avg_unique_ip_hour,max_unique_ip_hour,avg_unique_ip_day,max_unique_ip_day,is_mule,days_since_account_open,account_open_issue_flag,avg_balance_missing,active_tenure_days,monthly_avg_balance_missing,account_frozen_flag,zero_transaction_flag,least_common_channel_group,most_common_channel_group,uses_cdm,uses_crm,uses_both_atm,no_atm_deposit,duplicate_customer_flag,aadhaar_available
0,ACCT_000005,0,16380.55,1,0,1,0,1,0,15878.600,1,0,1,1,0,0,1,0,0,0,0.00,0,-15874.35,2,0.0,0,16380.55,1,0.00,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45425573.0,45900340.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1,792.0,1,0,5807,0,0,1,5,5,0,0,0,1,0,1.0
1,ACCT_000007,0,177.42,0,0,1,1,1,0,146.760,1,0,0,0,0,0,0,0,0,0,-1776537.23,1,0.00,0,0.0,0,0.00,0,177.42,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45425573.0,45900340.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1,792.0,1,0,5939,0,0,1,5,5,0,0,0,1,0,0.0
2,ACCT_000009,0,660.07,1,1,1,0,1,0,678.640,1,0,0,0,0,0,0,0,0,0,0.00,0,0.00,0,0.0,0,660.07,1,0.00,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45425573.0,45900340.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1,792.0,1,0,1734,0,0,1,5,5,0,0,0,1,0,-1.0
3,ACCT_000015,0,4551.00,0,1,1,0,1,0,4518.235,1,0,0,0,0,0,0,0,0,0,-700411.35,3,0.00,0,0.0,0,0.00,0,4467.10,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45425573.0,45900340.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1,792.0,1,1,3372,1,0,1,5,5,0,0,0,1,0,-1.0
4,ACCT_000016,0,10716.53,0,0,1,0,1,0,10715.690,1,0,0,0,0,0,0,1,0,0,0.00,0,0.00,0,0.0,0,0.00,0,10716.53,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45425573.0,45900340.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1,792.0,1,0,7477,0,0,1,5,5,0,0,0,1,0,0.0

In [24]:
x = df_merged.drop(columns=["account_id","is_mule"],axis = 1)
print(x.shape)
x.sample(5)

(64062, 112)

,account_status,avg_balance_x,product_family,nomination_flag,cheque_allowed,cheque_availed,kyc_compliant,rural_branch,monthly_avg_balance,pan_available,passport_available,mobile_banking_flag,internet_banking_flag,atm_card_flag,demat_flag,credit_card_flag,fastag_flag,joint_account_flag,nri_flag,loan_sum,loan_count,cc_sum,cc_count,od_sum,od_count,ka_sum,ka_count,sa_sum,sa_count,total_transactions,unique_mcc_count,max_mcc_frequency,mcc_max_amount,mcc_min_amount,unique_channel_count,max_channel_frequency,avg_unique_mcc_per_hour,avg_unique_mcc_per_day,avg_unique_channel_per_hour,avg_unique_channel_per_day,total_transaction_amount,avg_transaction_amount,max_transaction_amount,min_transaction_amount,std_transaction_amount,median_transaction_amount,total_credit_amount,total_debit_amount,max_credit_amount,max_debit_amount,credit_debit_ratio,avg_time_between_txn_sec,median_time_between_txn_sec,max_txn_1hr,max_txn_10min,max_txn_1day,avg_txn_per_day,avg_txn_per_hr,night_txn_rate,rapid_passthrough_count,unique_counterparty_count,repeated_counterparty_frequency,unique_credit_counterparty_count,unique_debit_counterparty_count,avg_unique_counterparty_1hr,max_unique_counterparty_1hr,avg_repeated_counterparty_freq_1hr,avg_unique_counterparty_1day,max_unique_counterparty_1day,avg_repeated_counterparty_freq_1day,geo_txn_count,geo_frac,unique_geo_count,geo_bbox_km,has_geo_flag,ip_txn_count,ip_frac,unique_ip_count,top_ip_count,top_ip_share,atm_deposit_count,atm_deposit_frac,min_balance,avg_balance_credit,avg_balance_debit,max_balance,clt_cash_ratio,loan_ratio,normal_ratio,ci_ratio,bi_ratio,ip_ratio,ic_ratio,avg_unique_ip_hour,max_unique_ip_hour,avg_unique_ip_day,max_unique_ip_day,days_since_account_open,account_open_issue_flag,avg_balance_missing,active_tenure_days,monthly_avg_balance_missing,account_frozen_flag,zero_transaction_flag,least_common_channel_group,most_common_channel_group,uses_cdm,uses_crm,uses_both_atm,no_atm_deposit,duplicate_customer_flag,aadhaar_available
12549,0,2579.56,1,0,1,0,1,0,2116.13,1,0,0,1,0,0,0,0,0,0,0.0,0,0.00,0,0.0,0,2579.56,1,0.00,0,4634.0,58.0,977.0,2921.0,2920.0,35.0,1915.0,1.0,2.0,1.0,2.0,1.328036e+08,28658.520807,20291300.00,-1104370.18,343282.907881,978.245,72873094.79,59930490.63,20291300.00,6725000.00,1.215960,29448.723937,15911.0,4.0,3.0,11.0,2.932911,0.122269,0.055460,17.0,5.0,0.998921,5.0,4.0,1.065555,3.0,0.010710,2.248443,5.0,0.216161,1808.0,0.390160,1808.0,572.354253,1.0,1620.0,0.349590,1620.0,1.0,0.000617,6.0,0.001295,-7162311.89,-2.289373e+05,-2.742683e+05,16163264.41,0.0,0.0,0.0,0.957272,0.031722,0.011006,0.0,1.0,3.0,2.0,6.0,1579.0,0,0,-1215,0,0,0,4,0,1,1,1,0,0,-1.0
50049,0,762.72,0,1,1,0,1,1,655.91,1,0,0,1,0,0,0,0,0,0,0.0,0,0.00,0,0.0,0,0.00,0,762.72,1,1468.0,49.0,303.0,2557.0,2920.0,31.0,621.0,1.0,2.0,1.0,2.0,2.606475e+07,17755.276390,1471599.02,-57000.00,85638.965655,1000.000,10690012.55,15374733.19,813844.23,1471599.02,0.695297,44994.635310,26931.0,3.0,2.0,9.0,1.918954,0.080057,0.053134,7.0,25.0,0.982970,25.0,24.0,1.069292,3.0,0.000608,2.229068,7.0,0.024648,595.0,0.405313,595.0,15.419730,1.0,535.0,0.364441,535.0,1.0,0.001869,0.0,0.000000,-5467674.65,-1.791313e+06,-1.754095e+06,1210383.18,0.0,0.0,0.0,0.953678,0.029292,0.017030,0.0,1.0,2.0,1.0,4.0,764.0,0,0,6423,0,0,0,2,0,0,0,0,1,0,1.0
50929,0,210234.13,0,0,1,0,1,0,213247.81,1,0,0,0,0,0,0,0,0,0,0.0,0,0.00,0,0.0,0,0.00,0,210234.13,1,1797.0,52.0,375.0,4106.0,9355.0,34.0,666.0,1.0,1.0,1.0,1.0,4.464473e+07,24844.034585,6203247.78,-1000.00,204264.359282,1000.000,15285330.71,29359399.44,885431.41,6203247.78,0.520628,87671.733296,62054.0,3.0,2.0,5.0,0.985738,0.041084,0.046188,5.0,22.0,0.987757,22.0,21.0,1.036973,2.0,0.000481,1.601098,5.0,0.015980,512.0,0.284919,512.0,15.403306,1.0,603.0,0.335559,603.0,1.0,0.001658,6.0,0.003339,-14757188.55,-8.719986e+06,-8.637302e+06,404648.08,0.0,0.0,0.0,0.932109,0.034502,0.033389,0.0,1.0,2.0,1.0,4.0,2765.0,0,0,5526,0,0,0,2,0,1,1,1,0,0,0.0
10094,0,-1748.53,0,1,1,0,1,0,-2040.24,1,0,0,0,0,0,0,0,0,0,0.0,0,0.00,0,0.0,0,0.00,0,-1748.53,1,1439.0,54.0,291.0,2921.0,5905.0,31.0,600.0,1.0,1.0,1.0,2.0,3.201542e+07,22248.381077,4822976.72,-32000.00,157391.484596,1000.000,14308528.39,17706891.98,4822976.72,1843500.00,0.808077,52162.228095,34568.0,3.0,2.0,7.0,1.655926,0.069060,0.049340,6.0,21.0,0.985407,21.0,20.0,1.039855,3.0,0.001449,1.958571,6.0,0.031361,597.0,0.414871,597.0,14.748796,1.0,507.0,0.352328,507.0,1.0,0.001972,1.0,0.000695,-3540813.84,2.432629e+06,2.326472e+06,5544351.12,0.0,0.0,0.0,0.963864,0.016678,0.019458,0.0,1.0,2.0,1.0,5.0,868.0,0,0,4494,0,0,0,3,0,1,0,0,0,0,-1.0
34427,0,8172.02,1,1,1,1,1,0,8115.58,1,0,1,1,1,0,1,0,0,0,0.0,0,-18456.68,1,0.0,0,1371.15,1,0.00,0,1275.0,49.0,269.0,5905.0,9384.0,33.0,487.0,1.0,1.0,1.0,2.0,4.317897e+07,33865.862157,11819000.00,-2500.00,389598.936960,900.000,18908684.84,24270289.41,6536474.23,11819000.00,0.779088,60091.502355,45980.5,3.0,2.0,7.0,1.437430,0.059952,0.049412,4.0,16.0,0.987451,16.0,15.0,1.041769,3.0,0.001229,1.818862,6.0,0.029605,484.0,0.379608,484.0,14.664952,1.0,449.0,0.352157,449.0,1.0,0.002227,3.0,0.002353,-15071138.14,-7.907682e+06,-7.853061e+06,875697.58,0.0,0.0,0.0,0.952941,0.024314,0.022745,0.0,1.0,2.0,1.0,4.0,886.0,0,1,9613,1,0,0,2,0,1,1,1,0,0,0.0

In [25]:
y_pred = lgbm.predict(x)
y_pred

array([0, 0, 0, ..., 0, 0, 0], shape=(64062,))

In [26]:
fraud = y_pred == 1

In [27]:
fraud

array([False, False, False, ..., False, False, False], shape=(64062,))

In [28]:
df = pd.DataFrame(y_pred, columns=["is_mule"])
df.is_mule.value_counts()

is_mule
0    62807
1     1255
Name: count, dtype: int64

In [29]:
df_test["is_mule"] = y_pred

In [37]:
df_test.head()

    account_id  is_mule  suspicious_start  suspicious_end
0  ACCT_000005        0               NaN             NaN
1  ACCT_000007        0               NaN             NaN
2  ACCT_000009        0               NaN             NaN
3  ACCT_000015        0               NaN             NaN
4  ACCT_000016        0               NaN             NaN

In [31]:
df_final = df_test
df_final.is_mule.value_counts()

is_mule
0    62807
1     1255
Name: count, dtype: int64

In [32]:
df_final.to_csv("prediction.csv",index=False)

In [33]:
df_final["suspicious_start"] = np.nan
df_final.shape

(64062, 3)

In [34]:
df_final["suspicious_end"] = np.nan
df_final.shape

(64062, 4)

In [35]:
df_final.sample(5)

        account_id  is_mule  suspicious_start  suspicious_end
8417   ACCT_026490        0               NaN             NaN
51002  ACCT_159991        0               NaN             NaN
31713  ACCT_099897        0               NaN             NaN
39677  ACCT_124764        0               NaN             NaN
7314   ACCT_022999        0               NaN             NaN

In [36]:
# df_final.to_csv("submission.csv",index = False)

In [38]:
df_final.is_mule.value_counts()

is_mule
0    62807
1     1255
Name: count, dtype: int64

In [39]:
df_final.head()

    account_id  is_mule  suspicious_start  suspicious_end
0  ACCT_000005        0               NaN             NaN
1  ACCT_000007        0               NaN             NaN
2  ACCT_000009        0               NaN             NaN
3  ACCT_000015        0               NaN             NaN
4  ACCT_000016        0               NaN             NaN

In [40]:
df_final1 = df_final.drop(columns=["suspicious_start","suspicious_end"],axis = 1)
df_final1.head()

    account_id  is_mule
0  ACCT_000005        0
1  ACCT_000007        0
2  ACCT_000009        0
3  ACCT_000015        0
4  ACCT_000016        0

In [41]:
df_final1.to_csv("s2.csv",index=False)